# Generated by Django 3.2.9 on 2021-11-25 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='RefContactNo',
            new_name='RefContactNo1',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='RefName',
            new_name='RefName1',
        ),
    ]
